/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo26.vistas;

/**
 *
 * @author macbookpro
 */
public class VistaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VistaInicio
     */
    public VistaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Alumno = new javax.swing.JMenu();
        FormularioDeAlumno = new javax.swing.JMenuItem();
        Materia = new javax.swing.JMenu();
        FormularioDeMateria = new javax.swing.JMenuItem();
        Administracion = new javax.swing.JMenu();
        ManejoDeInscripciones = new javax.swing.JMenuItem();
        ManipulacionDeNotas = new javax.swing.JMenuItem();
        Consultas = new javax.swing.JMenu();
        AlumnoPorMateria = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        Alumno.setText("Alumno");

        FormularioDeAlumno.setText("Formulario de Alumno");
        Alumno.add(FormularioDeAlumno);

        jMenuBar1.add(Alumno);

        Materia.setText("Materia");

        FormularioDeMateria.setText("Formulario de Materia");
        Materia.add(FormularioDeMateria);

        jMenuBar1.add(Materia);

        Administracion.setText("Administracion");

        ManejoDeInscripciones.setText("Manejo de Inscripciones");
        Administracion.add(ManejoDeInscripciones);

        ManipulacionDeNotas.setText("Manipulacion de notas");
        Administracion.add(ManipulacionDeNotas);

        jMenuBar1.add(Administracion);

        Consultas.setText("Consultas");

        AlumnoPorMateria.setText("Alumnos por Materia");
        Consultas.add(AlumnoPorMateria);

        jMenuBar1.add(Consultas);

        Salir.setText("Salir");
        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Administracion;
    private javax.swing.JMenu Alumno;
    private javax.swing.JMenuItem AlumnoPorMateria;
    private javax.swing.JMenu Consultas;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem FormularioDeAlumno;
    private javax.swing.JMenuItem FormularioDeMateria;
    private javax.swing.JMenuItem ManejoDeInscripciones;
    private javax.swing.JMenuItem ManipulacionDeNotas;
    private javax.swing.JMenu Materia;
    private javax.swing.JMenu Salir;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
